### PR TITLE
Changed all uses of println! to log! in tests

### PR DESCRIPTION
**Pull request by lurkny**
#101

### CODE REVIEW

**Review by evgenyigumnov — CHANGES_REQUESTED** [review]
Need to fix:

```
igumn@lenovo MINGW64 ~/shiva (lurkny-lurk-use-log-crate)
$ grep -r "println" --include="*.rs" . | grep -v target | grep -v third_party
./lib/src/core.rs:        println!("Loading image: {}", image_path);
./lib/src/docx.rs:            println!("unknown element");
./lib/src/docx.rs:                                eprintln!("Unknown paragraph element");
./lib/src/json.rs:        // println!("{:?}", generated_result.unwrap());
./lib/src/markdown.rs:                            // println!("The tag parsing is not implemented {:#?}", rest);
./lib/src/ods.rs:                    println!("Error reading sheet {}: {}", sheet_name, err);
./lib/src/pdf.rs:                println!("Warning - {}", warn.message);
./lib/src/pdf.rs:            // println!("2 {:?}", operand);
./lib/src/pdf.rs:        // println!("1 {:?}", operation.operator);
./lib/src/pdf.rs:        // println!("{:?}", parsed_document);
./lib/src/rtf.rs:            eprintln!("Unknown element in list: {:?}", element);
./lib/src/rtf.rs:                    eprintln!("Unknown element in list: {:?}", element);
./lib/src/text.rs:                // println!("list depth: {}", list_depth);
./lib/src/text.rs:        // println!("{:?}", document);
./lib/src/text.rs:        // println!("{:?}", generated_result.unwrap());
./lib/src/typst.rs:    println!("Downloading font file {}...", font_path.display());
./lib/src/typst.rs:        println!("Font file {} downloaded successfully!", font_path.display());
./lib/src/typst.rs:    println!("Downloading font file {}...", font_path.display());
./lib/src/typst.rs:    println!("Font file {} downloaded successfully!", font_path.display());
./lib/src/typst.rs:                    eprintln!(
./lib/src/typst.rs:                        eprintln!(
./lib/src/typst.rs:              //     eprintln!("Should implement element - {:?}", element);
./lib/src/xls.rs:                    println!("Error reading sheet {}: {}", sheet_name, err);
./lib/src/xlsx.rs:                    println!("Error reading sheet {}: {}", sheet_name, err);
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                                                                println!(
./lib/src/xml.rs:                                                                                println!(
./lib/src/xml.rs:                                                                    println!("Error: No value");
./lib/src/xml.rs:                                                                                        println!(
./lib/src/xml.rs:                                                                                        println!(
./lib/src/xml.rs:                                                                println!("Error: No value");
./lib/src/xml.rs:                                                                println!("Error: No value");
./lib/src/xml.rs:                                                    println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./lib/src/xml.rs:                                        println!("Error: No value");
./server/src/error.rs:        println!("-->> {:<12} - {self:?}", "INTO_RES");
./server/src/main.rs:    println!("-->>LISTENING on {:?}", listener.local_addr().unwrap());
./server/src/main.rs:    println!("-->> {:<12} - answer_server", "HANDLER");
./server/src/main.rs:    println!("-->> {:<12} - main_response_mapper", "RES_MAPPER");
./server/src/main.rs:    println!();
./server/src/web/routes_files.rs:                println!("-->> {:<12} - handler_convert_file input_extension_{input_extension}- output_extension_{output_format}", "HANDLER");
./server/src/web/routes_files.rs:                println!("-->> {:<12} - handler_convert_file input ZIP archive - output_extension_{output_format}", "HANDLER");
./server/src/web/routes_files.rs:    println!("upload file name: {}", file_name);
./server/src/web/routes_files.rs:    println!("upload file format: {}", file_extension);
./server/src/web/routes_files.rs:    println!("download file format: {}", output_format);
./server/src/web/routes_files.rs:    println!("Image files from the archive");
./server/src/web/routes_files.rs:        println!("- {:#?}", image_name);
./server/src/web/routes_files.rs:                println!("Error reading chunk: {:?}", e);
./server/src/web/routes_files.rs:        //println!("in ZIP {}.{}", file_name_in_archive.clone().unwrap(), file_extension_in_archive.clone().unwrap());
./server/src/web/routes_files.rs:    //println!("upload file name: {}", file_name);
./server/src/web/routes_files.rs:    //println!("upload file format: {}", file_extension);
./server/src/web/routes_files.rs:    //println!("download file format: {}", output_format);
```

**Comment by lurkny** [comment]
Ah, I was unsure if you wanted it only in tests or for every file.

**Comment by evgenyigumnov** [comment]
If some println is comment I think it should be uncomment and should be debug. not info.

you did:
```rust
        //println!("in ZIP {}.{}", file_name_in_archive.clone().unwrap(), file_extension_in_archive.clone().unwrap());
        //info!("in ZIP {}.{}", file_name_in_archive.clone().unwrap(), file_extension_in_archive.clone().unwrap());
```

you need do:
```
        //println!("in ZIP {}.{}", file_name_in_archive.clone().unwrap(), file_extension_in_archive.clone().unwrap());
        warn!("in ZIP {}.{}", file_name_in_archive.clone().unwrap(), file_extension_in_archive.clone().unwrap());        
```

**Review by evgenyigumnov — CHANGES_REQUESTED** [review]
Commented info! should be uncomment and will be debug!

**Review by evgenyigumnov — CHANGES_REQUESTED** [review]
```bash
igumn@lenovo MINGW64 ~/shiva (lurkny-lurk-use-log-crate)
$ cd lib
igumn@lenovo MINGW64 ~/shiva/lib (lurkny-lurk-use-log-crate)
$ cargo test text::tests::test -- --nocapture
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   C:\Users\igumn\shiva\shiva-wasm\Cargo.toml
workspace: C:\Users\igumn\shiva\Cargo.toml
warning: `shiva` (lib test) generated 12 warnings (run `cargo fix --lib -p shiva --tests` to apply 6 suggestions)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.44s
     Running unittests src\lib.rs (C:\Users\igumn\shiva\target\debug\deps\shiva-1e650c86cd25bd31.exe)

running 1 test
test text::tests::test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 37 filtered out; finished in 0.00s
```

As you see no one info output for test. I think you should add env_logger initialization for each tests where you use log.

Simple check is (in "lib" folder):

cargo test text::tests::test -- --nocapture

Complecs check is:

cargo test -- --nocapture

**Pull request merged**
